var a = parseInt(prompt("Enter a weight of a person:"));
var b = parseInt(prompt("Enter a weight of a person:"));
var c = parseInt(prompt("Enter a weight of a person:"));
var d = parseInt(prompt("Enter a weight of a person:"));
var e = parseInt(prompt("Enter a weight of a person:"));
var f = parseInt(prompt("Enter a weight of a person:"));
var sum = a+b+c+d+e+f;
var boys = parseInt(prompt("Number of a boys:"));
var boysWeight = parseInt(prompt("Enter a weight of a boys:"));
var weight = boys*boysWeight;
var total = weight - sum;
alert(total);
